Algoritmo "Variaveís"
// Disciplina   : j
// Professor   :
// Descrição   : Avarsi
// Autor(a)    : thais
// Data atual  : 27/10/2020
Var
// Seção de Declarações das variáveis 
// primeiro nome
// segundo nome
// idade
// cidade
// endereço

     primeiroNome, segundoNome, cidade, endereco: caractere
     idade: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo